-d D:\WORK\FPGA\Learning\SPI_Learning\impl\gwsynthesis\SPI_Learning.vg
-p GW1N-9C-eLQFP144-6
-pn GW1N-UV9EQ144C6/I5
-cst D:\WORK\FPGA\Learning\SPI_Learning\src\Spi_test.cst
-cfg D:\WORK\FPGA\Learning\SPI_Learning\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
